import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";
import Cursor from "@/components/Cursor";
import { neueHaas } from "@/app/fonts";

export const metadata: Metadata = {
  title: "MOSU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${neueHaas.variable} h-full antialiased`}>
      <body>
        <Cursor />
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
